# Generated by Django 5.2.7 on 2025-12-23 23:00

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_fin', models.DateTimeField(default=django.utils.timezone.now)),
                ('compteur', models.IntegerField(default=0)),
                ('status', models.CharField(default='termine', max_length=20)),
                ('nom_op1', models.CharField(default='', max_length=200)),
                ('op1_checked', models.BooleanField(default=False)),
                ('op1_comment', models.TextField(blank=True, default='', null=True)),
                ('op1_accuse_reception', models.BooleanField(default=False)),
                ('nom_op2', models.CharField(default='', max_length=200)),
                ('op2_checked', models.BooleanField(default=False)),
                ('op2_comment', models.TextField(blank=True, default='', null=True)),
                ('op2_accuse_reception', models.BooleanField(default=False)),
                ('nom_op3', models.CharField(default='', max_length=200)),
                ('op3_checked', models.BooleanField(default=False)),
                ('op3_comment', models.TextField(blank=True, default='', null=True)),
                ('op3_accuse_reception', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Dht11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(null=True)),
                ('hum', models.FloatField(null=True)),
                ('dt', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('compteur', models.IntegerField(default=0)),
                ('last_increment', models.DateTimeField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé')], default='en_cours', max_length=20)),
                ('nom_op1', models.CharField(default='Opération Corrective 1', max_length=200)),
                ('op1_checked', models.BooleanField(default=False)),
                ('op1_comment', models.TextField(blank=True, null=True)),
                ('op1_accuse_reception', models.BooleanField(default=False)),
                ('nom_op2', models.CharField(default='Opération Corrective 2', max_length=200)),
                ('op2_checked', models.BooleanField(default=False)),
                ('op2_comment', models.TextField(blank=True, null=True)),
                ('op2_accuse_reception', models.BooleanField(default=False)),
                ('nom_op3', models.CharField(default='Opération Corrective 3', max_length=200)),
                ('op3_checked', models.BooleanField(default=False)),
                ('op3_comment', models.TextField(blank=True, null=True)),
                ('op3_accuse_reception', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('operateur1', 'Opérateur 1'), ('operateur2', 'Opérateur 2'), ('operateur3', 'Opérateur 3'), ('visiteur', 'Visiteur')], default='visiteur', max_length=20)),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_temperature', models.FloatField(default=2.0)),
                ('max_temperature', models.FloatField(default=8.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seuil de Température',
                'verbose_name_plural': 'Seuils de Température',
            },
        ),
        migrations.CreateModel(
            name='IncidentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='DHT.incident')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='incident',
            name='op1_operateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_op1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='op2_operateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_op2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incident',
            name='op3_operateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_op3', to=settings.AUTH_USER_MODEL),
        ),
    ]
