# Generated by Django 5.2.7 on 2025-12-24 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archiveincident',
            options={'ordering': ['-date_debut'], 'verbose_name': 'Archive Incident', 'verbose_name_plural': 'Archives Incidents'},
        ),
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-date_debut'], 'verbose_name': 'Incident', 'verbose_name_plural': 'Incidents'},
        ),
        migrations.AlterModelOptions(
            name='incidentcomment',
            options={'ordering': ['created_at'], 'verbose_name': 'Commentaire Incident', 'verbose_name_plural': 'Commentaires Incidents'},
        ),
        migrations.RemoveField(
            model_name='archiveincident',
            name='op1_accuse_reception',
        ),
        migrations.RemoveField(
            model_name='archiveincident',
            name='op2_accuse_reception',
        ),
        migrations.RemoveField(
            model_name='archiveincident',
            name='op3_accuse_reception',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='op1_accuse_reception',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='op2_accuse_reception',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='op3_accuse_reception',
        ),
        migrations.RemoveField(
            model_name='temperaturethreshold',
            name='max_temperature',
        ),
        migrations.RemoveField(
            model_name='temperaturethreshold',
            name='min_temperature',
        ),
        migrations.AddField(
            model_name='archiveincident',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archiveincident',
            name='op1_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archiveincident',
            name='op1_operateur_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='archiveincident',
            name='op2_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archiveincident',
            name='op2_operateur_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='archiveincident',
            name='op3_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='archiveincident',
            name='op3_operateur_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='archiveincident',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='op1_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='op2_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='op3_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='temperaturethreshold',
            name='max_temp',
            field=models.FloatField(default=8.0, verbose_name='Température Maximum (°C)'),
        ),
        migrations.AddField(
            model_name='temperaturethreshold',
            name='min_temp',
            field=models.FloatField(default=2.0, verbose_name='Température Minimum (°C)'),
        ),
        migrations.AlterField(
            model_name='temperaturethreshold',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('operateur1', 'Opérateur 1'), ('operateur2', 'Opérateur 2'), ('operateur3', 'Opérateur 3'), ('visiteur', 'Visiteur')], default='visiteur', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Utilisateur',
                'verbose_name_plural': 'Profils Utilisateurs',
            },
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
