# Generated by Django 5.2.7 on 2025-11-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('compteur', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('op1_checked', models.BooleanField(default=False)),
                ('op1_comment', models.TextField(blank=True)),
                ('op2_checked', models.BooleanField(default=False)),
                ('op2_comment', models.TextField(blank=True)),
                ('op3_checked', models.BooleanField(default=False)),
                ('op3_comment', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ArchiveIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('nombre_incidents', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date',)},
            },
        ),
    ]
