# Generated by Django 5.2.7 on 2026-01-02 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0002_alter_archiveincident_options_alter_incident_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archiveincident',
            options={'ordering': ['-date_debut']},
        ),
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-date_debut']},
        ),
        migrations.AlterModelOptions(
            name='incidentcomment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='archiveincident',
            name='op1_operateur_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='archiveincident',
            name='op2_operateur_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='archiveincident',
            name='op3_operateur_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='archiveincident',
            name='status',
            field=models.CharField(choices=[('en_cours', 'En cours'), ('termine', 'Terminé')], default='termine', max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='op1_operateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='op1_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incident',
            name='op2_operateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='op2_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incident',
            name='op3_operateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='op3_incidents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='temperaturethreshold',
            name='max_temp',
            field=models.FloatField(default=8.0),
        ),
        migrations.AlterField(
            model_name='temperaturethreshold',
            name='min_temp',
            field=models.FloatField(default=2.0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('operateur1', 'Operateur 1'), ('operateur2', 'Operateur 2'), ('operateur3', 'Operateur 3'), ('visiteur', 'Visiteur')], default='visiteur', max_length=20),
        ),
    ]
