# Generated by Django 5.2.7 on 2026-01-02 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0003_alter_archiveincident_options_alter_incident_options_and_more'),
    ]

    operations = [
        
    ]
