# Generated by Django 5.2.7 on 2026-01-02 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0004_auto_20260102_0141'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='accuse_reception',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='accuse_reception_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='accuse_reception_operateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accuse_reception_incidents', to=settings.AUTH_USER_MODEL),
        ),
    ]
