# Generated by Django 5.2.7 on 2026-01-02 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0005_incident_accuse_reception_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_temp', models.FloatField(default=2.0)),
                ('max_temp', models.FloatField(default=8.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seuil de Température',
                'verbose_name_plural': 'Seuils de Température',
            },
        ),
    ]
