# Generated by Django 5.2.7 on 2026-01-02 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0005_incident_accuse_reception_and_more'),
    ]

    operations = [
        
    ]
