# Generated by Django 5.2.7 on 2026-01-02 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0006_auto_20260102_2206'),
    ]

    operations = [
       
    ]
