# Generated by Django 5.2.7 on 2026-01-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0007_create_userprofile_table'),
    ]

    operations = [
        
    ]
